#Pull base image
FROM python:3.10.10

#SET ENVIRONMENT VARIABLES
#WE DONT WANT .pyc FILES which makes it cluttered
ENV PYTHONDONTWRITEBYTECODE 1
#WE DONT WANT PYTHON TO BUFFER INPUT AND OUTPUT. SO WE DISABLE IT
ENV PYTHONBUFFERED 1

#SET WROK DIRECTORY
#INSTEAD OF USING LONG COMMAND LINE STATEMENTS TO NAVIGATE 
#BY DEFAULT WE GET COMMAND LINE HERE
WORKDIR /code

#INSTALL DEPENDENCIES
#COPY THE PIPFILE AND PIPFILE.LOCK
COPY Pipfile Pipfile.lock /code/
#INSTALL PIPENV AND THEN INSTALL THE DEPENDENCIES
#--SYSTEM MEANS INSTALL DEPENDENCIES GLOBALLY
#IF WE DONT USE SYSTEM, BY DEFAULT IT INSTALL VIRTUAL ENVRIONMENT
RUN pip install pipenv && pipenv install --system

#COPY THE LOCAL CODE TO CODE DIRECTORY
COPY . /code/